config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#one'

  get 'pages/two'
  get 'pages/one'
  get 'pages/ctys'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_users

  def one
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def two
    respond_to do |format|
      format.html
      format.js
    end
  end

  def ctys
    @get_all_states = get_all_states
    respond_to do |format|
      format.js
    end
  end

  def get_all_states()
    ISO3166::Country.find_country_by_alpha2(params['op1']).subdivisions.map do |state|
      [state.second['name'], state.first]
    end
  end

  private

    def check_users
      if User.first.nil?
        populate
      end
    end

    def populate
      file = Rails.root.join('vendor/excels/datos.xlsx')
      xlsx = Roo::Spreadsheet.open(file, extension: :xlsx)
      xlsx.each_with_pagename do |name, sheet|
        sheet.each(nombre: 'nombre', edad: 'edad') do |hash|
          User.create(hash)
        end
      end
    end

end

app/helpers/a_b_helper.rb
module ABHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_all_countries
    ISO3166::Country.all_names_with_codes('es')
  end

  
  def dime_si(val)
    true
  end
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxclass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/ctys.js.erb
$('#city option').remove()
<% @get_all_states.each do |array| %>

	$('#city').append("<option><%= array.first %></option>")
		
<% end %>

app/views/pages/one.html.erb
<!-- 	<a href="<%= pages_two_path %>" data-turbolinks="true" data-remote: 'true'> click me </a>
 -->
<form>
	<!--Countries-->
	<% if dime_si(10) %>
		<select id='cty'>
			<% get_all_countries.each do |array| %>
			  <option value="<%= array.last %>"><%= array.first %></option>
			<% end %>
		</select>
		<!--Cities-->
		<select id='city'>
			<option>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
		</select>
	<% end %>

</form>


//Valor en el combo de city se manda a servidor como argumento.

app/views/pages/one.js.erb
alert('entra');

app/views/pages/one.json.erb
{
  'a': 'b'
}

app/views/pages/two.html.erb
some this

app/views/pages/two.js.erb
$('a').css({
  color: 'red',
  'font-size': '40px'
})